baseURL = 'https://rukd3.github.io/GBM/'
languageCode = 'en-us'
title = 'CLyde Zhang'
theme = "Anatole" 

[params]
title = "CLyde Zhang"
author = "CLyde Zhang"
description = "game designer & CFX artist"
profilePicture = "images/profile.jpg"
contentratio = 0.73
displayMode = "dark"
mainSections = []



[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:1095135154@qq.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://rukd3.github.io/GBM/"


[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[menu]

  [[menu.main]]
  name = "	project	"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "	art works	"
  weight = 200
  identifier = "art works"
  url = "/art works/"

  [[menu.main]]
  name = "game experience"
  weight = 300
  identifier = "game experience"
  url = "/post/game ex"

  [[menu.main]]
  name = "about me"
  weight = 400
  identifier = "about"
  url = "/about"